---
title: "HeavyTailed"
author: "Jonathan Rosenblatt"
date: "8/2/2017"
output: html_document
editor_options: 
  chunk_output_type: console
---



```{r}
n.permutations <- 3e2
n.replications <-  1e2
```


```{r preliminaries}
file.name <- "file9"
setwd('~/workspace/permuting_accuracy/Round3/')

balance <- TRUE   # set for TRUE for balanced folding ana refolding.
p <- 23
n <- 4e1 # total sample size-> n/2 in each group.
n.folds <- 4

source('Gilron Effect of Cross Validatino.R')

## Signal in location
effects <- seq(0, 10, length=3) # change in location


Sigma <- diag(p)
Sigma.inv <- solve(Sigma)
# lattice::levelplot(Sigma)
direction0 <- rep(1,p)
maha <- direction0 %*% solve(Sigma) %*% direction0 %>% c
direction <- direction0 / sqrt(n/2*maha)
```


## Fixed folds. Cross-Validated. All in one.
```{r}
RhpcBLASctl::blas_set_num_threads(1)
registerDoMC(cores=100)
```


```{r independent noise variable folds}
pvals.1.9 <- foreach(j=1:n.replications, .combine=rbind) %dopar%{
  foreach(effect=effects, .combine=rbind)  %do% {
    
    labels <- sample(c(rep(TRUE, n/2), rep(FALSE,n/2))) # group assignemt labels
    
    ## t noise
    .noise <- rmvt(n=n, sigma = Sigma, df=3)
    
    ## Shift alternative:
    noise <- .noise
    shift <- matrix(effect * direction, nrow=20, ncol=23, byrow = TRUE)
    noise[labels,] <- noise[labels,] + shift
    
    ## Compute observed statistic
    x1 <- noise[labels,]
    x2 <- noise[!labels,]
    
    ## Asign observations to folds. Use the simple label structure to balance folds.
    fold.ids <- balanced_folding(labels, n.folds, balance = balance)
    # capture.output(table(fold.ids, labels), file=balance.log, append = TRUE)
    
    # Observables 
        ts <-statistics(x1 = x1, 
                    x2 = x2, 
                    Sigma.inv = Sigma.inv, 
                    noise = noise, 
                    labels = labels, 
                    fold.ids = fold.ids)

    
    # Prepare to permute
    old.labels <- labels
    old.folds.ids <- fold.ids
    
    # Initialize permuted statistics
    permuted <- matrix(NA, ncol=length(ts), nrow=n.permutations)
    
    for(i in 1:n.permutations){
      # i <- 1
      
      labels <- sample(labels) # make permutation
      fold.ids <- balanced_folding(labels, n.folds, balance) # refold

      x1 <- noise[labels,]
      x2 <- noise[!labels,]
      
      permuted[i,] <- statistics(x1 = x1, 
                                 x2 = x2,
                                 Sigma.inv =Sigma.inv, 
                                 noise = noise,
                                 labels = labels,
                                 fold.ids = fold.ids)
    } # End permutation
    
    ## Compute p-vals for each statistic
    pvals <- rep(NA, length(ts))
    for(i in seq_along(ts)){
      pvals[i] <- mean(ts[i]<=permuted[,i], na.rm=TRUE)
    }
    names(pvals) <- names(ts)
    
    
    c(effect=effect, pvals) 
  }
} 

pbPost(type = "note", body = "Done", the.message)
save.image(file=paste(file.name,".RData", sep=''))
```



```{r analyze multiple effects}
# load("file9.RData")
source('prepare_graphics.R')
plot(plot.3)
```


```{r}
pdf(file = paste('Output/',file.name,'.pdf', sep=''))
plot(plot.3)
dev.off()
```


