---
title: "Basic setup"
author: "Jonathan Rosenblatt"
date: "23/1/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r}
n.permutations <- 1e3
n.replications <-  2e5
```


```{r preliminaries}
file.name <- "file2"
setwd('~/workspace/permuting_accuracy/Round4/')

balance <- TRUE   # set for TRUE for balanced folding ana refolding.
with.cv <- TRUE
p <- 23
n <- 40 # total sample size-> n/2 in each group.
n.folds <- 4

source('Gilron Effect of Cross Validatino.R')

effects <- seq(0, 10, length=3) # change in location

Sigma <- diag(p)
Sigma.inv <- solve(Sigma)
```

```{r}
direction0 <- rep(1,p)
maha <- direction0 %*% Sigma.inv %*% direction0 %>% c
direction <-  direction0 / sqrt(n/2*maha)
```


## Fixed folds. Cross-Validated. All in one.
```{r}
RhpcBLASctl::blas_set_num_threads(1)
registerDoMC(cores=100)
```


```{r independent noise variable folds}
pvals.1.9 <- foreach(j=1:n.replications, .combine=rbind) %dopar%{
  foreach(effect=effects, .combine=rbind)  %do% {
    
    labels <- sample(c(rep(TRUE, n/2), rep(FALSE,n/2))) # group assignemt labels
    
    ## Gaussian noise, Shift alternative:
    # effect <- effects[[1]]
    
    shift <- matrix(effect * direction, nrow=n/2, ncol=p, byrow = TRUE)
    noise <- matrix(rnorm(n*p), ncol=p, nrow=n)
    noise[labels,] <- noise[labels,] + shift
    
    ## Compute observed statistic
    x1 <- noise[labels,]
    x2 <- noise[!labels,]
    
    ## Asign observations to folds. Use the simple label structure to balance folds.
    fold.ids <- balanced_folding(labels, n.folds, TRUE)
    # capture.output(table(fold.ids, labels), file=balance.log, append = TRUE)
    
    # Observables 
    ts <-statistics(x1 = x1, 
                    x2 = x2, 
                    Sigma.inv = Sigma.inv, 
                    noise = noise, 
                    labels = labels, 
                    fold.ids = fold.ids, 
                    with.cv=with.cv)
    
    # Prepare to permute
    old.labels <- labels
    old.folds.ids <- fold.ids
    
    # Initialize permuted statistics
    permuted <- matrix(NA, ncol=length(ts), nrow=n.permutations)
    
    for(i in 1:n.permutations){
      # i <- 1
      
      labels <- sample(labels) # label switching
      fold.ids <- balanced_folding(labels, n.folds, TRUE) # refold
      x1 <- noise[labels,]
      x2 <- noise[!labels,]
      
      permuted[i,] <- statistics(x1 = x1, 
                                 x2 = x2,
                                 Sigma.inv =Sigma.inv, 
                                 noise = noise,
                                 labels = labels,
                                 fold.ids = fold.ids,
                                 with.cv=with.cv)
    } # End permutation
    
    # Compute p-vals for each statistic
    pvals <- rep(NA, length(ts))
    for(i in seq_along(ts)){
      # i <- 1
      pvals[i] <- mean(permuted[,i]>=ts[i], na.rm=TRUE)
    }
    names(pvals) <- names(ts)
    
    c(effect=effect, pvals, replication=j) 
  }
} 
  
pbPost(type = "note", body = "Done", the.message)
# save.image(file=paste(file.name,".RData", sep=''))
```


```{r}
# load('file2.RData')
source('prepare_graphics.R')
plot(plot.3)
```

```{r}
pdf(file = paste('Output/',file.name,'.pdf', sep=''))
plot(plot.3)
dev.off()
```

There is indeed a problem with p-values:

```{r}
pvals.melt[effect==0,.(Power=mean(value<0.05)),.(effect,statistic)]
pvals.melt[effect==0,value,.(effect,statistic)] %>% 
  ggplot(aes(value))+
  stat_ecdf(geom = "step")+
  facet_wrap(~statistic)
```

     effect     statistic Power
 1:      0    Oracle.Cov 0.050
 2:      0     Hotelling 0.051
 3:      0       Schafer 0.049
 4:      0        Goeman 0.050
 5:      0    Srivastava 0.050
 6:      0       Gretton 0.057
 7:      0          dCOV 0.051
 8:      0         Simes 0.058
 9:      0           Cai 0.050
10:      0      lda.CV.1 0.047
11:      0    lda.noCV.1 0.023
12:      0   svm.CV.c100 0.038
13:      0   svm.CV.c001 0.053
14:      0    svm.CV.cCV 0.043
15:      0 svm.noCV.c100 0.000
16:      0 svm.noCV.c001 0.037

